a commit was repair
paion-data/elide-doc pull request #5
Opened 2024-03-22 16:42 UTC by Doom9527

I revoked the previous pull and sent a new one

2024-03-23 01:14 UTC, QubitPi requested changes
The change looks good except for just a minor catch.

I also noticed that you closed [the other PR](https://github.com/paion-data/elide-doc/pull/4). While you could definitely re-open a new PR like this one. We actually don't open a new PR if code review doesn't pass. Simply addressing the review comments by pushing new commits to the existing PR is all good 😉 

Also, the PR's title is much better with aligning itself with the [issue title](Implement CI/CD)

2024-03-23 01:14 UTC, QubitPi commented on .github/workflows/ci-cd.yml
> +    name: Tests Homepage Build
The `name` field describes that this job does.

A better name would be `Tests Documentation Build`, since we are CI/CDing elide *documentation*

2024-03-26 08:04 UTC, QubitPi requested changes

2024-03-26 08:04 UTC, QubitPi commented on .github/workflows/ci-cd.yml
> +    name: Tests Homepage Build
```diff
- Tests Homepage Build
+ Tests Documentation Build
```

2024-03-28 03:45 UTC, Doom9527 commented on .github/workflows/ci-cd.yml
> +    name: Tests Homepage Build
This task has been completed.

2024-03-28 04:21 UTC, QubitPi approved these changes
👍🏻 Looks good

2024-03-28 13:53 UTC, merged